//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:results-schema", IsNullable=false)]
public partial class ResultFileV7 {
    
    private string headerField;
    
    private ResultFileV7Gradeset[] gradesetNodeField;
    
    private ResultFileV7Resultset[] resultsetNodeField;
    
    private ResultFileV7Aspect[] aspectNodeField;
    
    private ResultFileV7Result[] resultNodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Gradeset", IsNullable=false)]
    public ResultFileV7Gradeset[] GradesetNode {
        get {
            return this.gradesetNodeField;
        }
        set {
            this.gradesetNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resultset", IsNullable=false)]
    public ResultFileV7Resultset[] ResultsetNode {
        get {
            return this.resultsetNodeField;
        }
        set {
            this.resultsetNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Aspect", IsNullable=false)]
    public ResultFileV7Aspect[] AspectNode {
        get {
            return this.aspectNodeField;
        }
        set {
            this.aspectNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Result", IsNullable=false)]
    public ResultFileV7Result[] ResultNode {
        get {
            return this.resultNodeField;
        }
        set {
            this.resultNodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7Gradeset {
    
    private string exporterRefIdField;
    
    private string refIdField;
    
    private string moduleField;
    
    private string supplierField;
    
    private string supplierRefIdField;
    
    private string externalIdField;
    
    private string nameField;
    
    private string notesField;
    
    private string createDateField;
    
    private string editDateField;
    
    private ResultFileV7GradesetGradesetHistory[] gradesetHistoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExporterRefId {
        get {
            return this.exporterRefIdField;
        }
        set {
            this.exporterRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RefId {
        get {
            return this.refIdField;
        }
        set {
            this.refIdField = value;
        }
    }
    
    /// <remarks/>
    public string Module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    public string Supplier {
        get {
            return this.supplierField;
        }
        set {
            this.supplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SupplierRefId {
        get {
            return this.supplierRefIdField;
        }
        set {
            this.supplierRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public string CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string EditDate {
        get {
            return this.editDateField;
        }
        set {
            this.editDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GradesetHistory")]
    public ResultFileV7GradesetGradesetHistory[] GradesetHistory {
        get {
            return this.gradesetHistoryField;
        }
        set {
            this.gradesetHistoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7GradesetGradesetHistory {
    
    private string startDateField;
    
    private string endDateField;
    
    private string valuesetAgencyField;
    
    private ResultFileV7GradesetGradesetHistoryGrade[] gradeField;
    
    /// <remarks/>
    public string StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    public string ValuesetAgency {
        get {
            return this.valuesetAgencyField;
        }
        set {
            this.valuesetAgencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Grade")]
    public ResultFileV7GradesetGradesetHistoryGrade[] Grade {
        get {
            return this.gradeField;
        }
        set {
            this.gradeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7GradesetGradesetHistoryGrade {
    
    private string titleField;
    
    private string descriptionField;
    
    private string rankOrderField;
    
    private string valueField;
    
    private string colorField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string RankOrder {
        get {
            return this.rankOrderField;
        }
        set {
            this.rankOrderField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7Resultset {
    
    private string exporterRefIdField;
    
    private string resultsetRefIdField;
    
    private string resultsetModuleField;
    
    private string resultsetSupplierField;
    
    private string resultsetSupplierRefIdField;
    
    private string resultsetExternalIdField;
    
    private string nameField;
    
    private string createDateField;
    
    private string editDateField;
    
    private string startDateField;
    
    private string endDateField;
    
    private string keyStageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExporterRefId {
        get {
            return this.exporterRefIdField;
        }
        set {
            this.exporterRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetRefId {
        get {
            return this.resultsetRefIdField;
        }
        set {
            this.resultsetRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string ResultsetModule {
        get {
            return this.resultsetModuleField;
        }
        set {
            this.resultsetModuleField = value;
        }
    }
    
    /// <remarks/>
    public string ResultsetSupplier {
        get {
            return this.resultsetSupplierField;
        }
        set {
            this.resultsetSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetSupplierRefId {
        get {
            return this.resultsetSupplierRefIdField;
        }
        set {
            this.resultsetSupplierRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string ResultsetExternalId {
        get {
            return this.resultsetExternalIdField;
        }
        set {
            this.resultsetExternalIdField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string EditDate {
        get {
            return this.editDateField;
        }
        set {
            this.editDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string KeyStage {
        get {
            return this.keyStageField;
        }
        set {
            this.keyStageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7Aspect {
    
    private string exporterRefIdField;
    
    private string gradesetRefIdField;
    
    private string gradesetModuleField;
    
    private string gradesetSupplierField;
    
    private string gradesetExternalIdField;
    
    private string refIdField;
    
    private string moduleField;
    
    private string supplierField;
    
    private string supplierRefIdField;
    
    private string externalIdField;
    
    private string nameField;
    
    private string columnHeadingField;
    
    private string descriptionField;
    
    private string createDateField;
    
    private string editDateField;
    
    private string typeField;
    
    private string keyStage1Field;
    
    private string keyStage2Field;
    
    private string keyStage3Field;
    
    private string version5Field;
    
    private string progressGridField;
    
    private ResultFileV7AspectMarkset[] marksetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExporterRefId {
        get {
            return this.exporterRefIdField;
        }
        set {
            this.exporterRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GradesetRefId {
        get {
            return this.gradesetRefIdField;
        }
        set {
            this.gradesetRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GradesetModule {
        get {
            return this.gradesetModuleField;
        }
        set {
            this.gradesetModuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GradesetSupplier {
        get {
            return this.gradesetSupplierField;
        }
        set {
            this.gradesetSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GradesetExternalId {
        get {
            return this.gradesetExternalIdField;
        }
        set {
            this.gradesetExternalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RefId {
        get {
            return this.refIdField;
        }
        set {
            this.refIdField = value;
        }
    }
    
    /// <remarks/>
    public string Module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    public string Supplier {
        get {
            return this.supplierField;
        }
        set {
            this.supplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SupplierRefId {
        get {
            return this.supplierRefIdField;
        }
        set {
            this.supplierRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalId {
        get {
            return this.externalIdField;
        }
        set {
            this.externalIdField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string ColumnHeading {
        get {
            return this.columnHeadingField;
        }
        set {
            this.columnHeadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string EditDate {
        get {
            return this.editDateField;
        }
        set {
            this.editDateField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string KeyStage1 {
        get {
            return this.keyStage1Field;
        }
        set {
            this.keyStage1Field = value;
        }
    }
    
    /// <remarks/>
    public string KeyStage2 {
        get {
            return this.keyStage2Field;
        }
        set {
            this.keyStage2Field = value;
        }
    }
    
    /// <remarks/>
    public string KeyStage3 {
        get {
            return this.keyStage3Field;
        }
        set {
            this.keyStage3Field = value;
        }
    }
    
    /// <remarks/>
    public string Version5 {
        get {
            return this.version5Field;
        }
        set {
            this.version5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ProgressGrid {
        get {
            return this.progressGridField;
        }
        set {
            this.progressGridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Markset")]
    public ResultFileV7AspectMarkset[] Markset {
        get {
            return this.marksetField;
        }
        set {
            this.marksetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7AspectMarkset {
    
    private string[] startDateField;
    
    private string[] endDateField;
    
    private string[] minValueField;
    
    private string[] maxValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StartDate")]
    public string[] StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EndDate", IsNullable=true)]
    public string[] EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MinValue", IsNullable=true)]
    public string[] MinValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MaxValue", IsNullable=true)]
    public string[] MaxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:results-schema")]
public partial class ResultFileV7Result {
    
    private string exporterRefIdField;
    
    private string aspectRefIdField;
    
    private string aspectModuleField;
    
    private string aspectSupplierField;
    
    private string aspectExternalIdField;
    
    private string resultsetRefIdField;
    
    private string resultsetModuleField;
    
    private string resultsetSupplierField;
    
    private string resultsetExternalIdField;
    
    private string refIdField;
    
    private string moduleField;
    
    private string studentField;
    
    private string surnameField;
    
    private string forenameField;
    
    private string genderField;
    
    private string dOBField;
    
    private string schoolField;
    
    private string lEANumberField;
    
    private string schoolNumberField;
    
    private string dateField;
    
    private string resultValueField;
    
    private string resultNotesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExporterRefId {
        get {
            return this.exporterRefIdField;
        }
        set {
            this.exporterRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AspectRefId {
        get {
            return this.aspectRefIdField;
        }
        set {
            this.aspectRefIdField = value;
        }
    }
    
    /// <remarks/>
    public string AspectModule {
        get {
            return this.aspectModuleField;
        }
        set {
            this.aspectModuleField = value;
        }
    }
    
    /// <remarks/>
    public string AspectSupplier {
        get {
            return this.aspectSupplierField;
        }
        set {
            this.aspectSupplierField = value;
        }
    }
    
    /// <remarks/>
    public string AspectExternalId {
        get {
            return this.aspectExternalIdField;
        }
        set {
            this.aspectExternalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetRefId {
        get {
            return this.resultsetRefIdField;
        }
        set {
            this.resultsetRefIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetModule {
        get {
            return this.resultsetModuleField;
        }
        set {
            this.resultsetModuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetSupplier {
        get {
            return this.resultsetSupplierField;
        }
        set {
            this.resultsetSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ResultsetExternalId {
        get {
            return this.resultsetExternalIdField;
        }
        set {
            this.resultsetExternalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RefId {
        get {
            return this.refIdField;
        }
        set {
            this.refIdField = value;
        }
    }
    
    /// <remarks/>
    public string Module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    public string Student {
        get {
            return this.studentField;
        }
        set {
            this.studentField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Forename {
        get {
            return this.forenameField;
        }
        set {
            this.forenameField = value;
        }
    }
    
    /// <remarks/>
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public string DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string School {
        get {
            return this.schoolField;
        }
        set {
            this.schoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string LEANumber {
        get {
            return this.lEANumberField;
        }
        set {
            this.lEANumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SchoolNumber {
        get {
            return this.schoolNumberField;
        }
        set {
            this.schoolNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string ResultValue {
        get {
            return this.resultValueField;
        }
        set {
            this.resultValueField = value;
        }
    }
    
    /// <remarks/>
    public string ResultNotes {
        get {
            return this.resultNotesField;
        }
        set {
            this.resultNotesField = value;
        }
    }
}
