exec sims.adm_pix_ApplicationDetail_Save @user_id=2,@application_xml='<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?><DetailedApplication UniquePupilNoAttribute="A12345677842936d26e077453ca12983d6303177ee" YearTaughtInAttribute="30" EnrollmentModeAttribute="2" AdmissionDateAttribute="2018-04-30T09:00:47" FSMReviewDateAttribute="2017-10-21T00:00:00" IsPublicFundingNotEligibleAttribute="F" EthnicityAttribute="300" EthnicDataSourceAttribute="2018" EthnicDatasourceAttribute="2018" LegalForenameAttribute="Dang 7" MiddleNameAttribute="Dang" LegalSurnameAttribute="Dinh" PreferredSurnameAttribute="Dinh" PreferredForenameAttribute="Dang 7" DateOfBirthAttribute="1987-07-07T00:00:00" GenderAttribute="M" UPNAttribute="A12345677842936d26e077453ca12983d6303177ee" ForenameAttribute="Dang 7" ChosenNameAttribute="Dang 7" SurnameAttribute="Dinh" IDAttribute="-1" AppliedIntakeGroupAttribute="1041" AppliedAdmissionGroupAttribute="1041" StatusAttribute="4" State="1"><Applicant 
DateOfBirthAttribute="1987-07-07T00:00:00" AgeAttribute="31 years, 10 months" SurnameAttribute="Dinh" ForenameAttribute="Dang 7" MiddleNameAttribute="Dang" 
ChosenNameAttribute="Dang 7" LegalSurnameAttribute="Dinh" GenderAttribute="M" /><DietaryNeeds /><ParamedicalSupports /><ParentalConsents /><StudentDietaryPreferences 
/><ApplicationResidencyCollection><ApplicationResidency ResidenceIDAttribute="-4" AddressTypeAttribute="1" IDAttribute="-38" PostcodeAttribute="ZZ99 9XX" CountryAttribute="215" 
StreetAttribute="Addres Line 1Addres Line 2" ValidatedAttribute="0" HouseNumberAttribute="" TownAttribute="" HouseNameAttribute="House name" CountyAttribute="Somewhereshire" 
ApartmentAttribute="" State="1" AddressId="-38"><Address><row AddressId="-38" HouseName="House name" Street="Addres Line 1Addres Line 2" County="Somewhereshire" Country_id="215" 
Postcode="ZZ99 9XX" Validated="F" status="I" /></Address></ApplicationResidency></ApplicationResidencyCollection><ApplicationRelations /><ApplicationNationalityCollection 
/><TravellerDetails /><ApplicationMedicalEvents /><ApplicationMedicalConditions /><FreeSchoolMealCollection /><FreeSchoolMilkCollection /><FreeSchoolTransportCollection 
/><CareRecords /><ChildProtectionRecords /><SchoolHistoryCollection><SchoolHistory IDAttribute="-1" StartDateAttribute="2009-09-13T00:00:00" 
EndDateAttribute="2011-07-22T00:00:00" IsCurrentSchoolAttribute="F" ReasonForLeavingAttribute="10" EnrollmentModeAttribute="2" DateOfArrivalAttribute="2009-09-13T00:00:00" 
DateOfLeavingAttribute="2011-07-22T00:00:00" State="1" SchoolIDAttribute="1" /></SchoolHistoryCollection><CriterionResults /><CommunicationSummaries /><VisitSummarys 
/><emails><email><person_id>0</person_id><email_id>-3</email_id><location>H</location><main>T</main><primary>T</primary><email_address>name@domain.co.uk</email_address><notes></notes><status>N</status><use_for_fees_documents>False</use_for_fees_documents></email></emails><phones><phone><person_id>0</person_id><telephone_id>1</telephone_id><device>T</device><location>H</location><number>01234 
999999</number><main>T</main><primary>T</primary><notes>H</notes><status>N</status></phone></phones></DetailedApplication>',@medical_condition_document_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@medical_event_document_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@medical_note_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@pep_document_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@other_telephones_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@deleted_communications_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data />',@cohabitees_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@photo=default,@issue_upn='P',@delete_former_upn=0,@delete_upn=0,@previous_names_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@medical_practice_XML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@disabilityXML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@free_school_meal_XML='<?xml version="1.0" encoding="ISO-8859-1"?><data> <row BaseGroupId=''60'' StartDate=''2016-10-23T00:00:00'' EndDate=''2017-12-24T00:00:00'' CountryId=''1'' /> <row BaseGroupId=''60'' StartDate=''2016-03-23T00:00:00'' CountryId=''1'' /></data>',@LinkedAgentsXML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@LinkedAgenciesXML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@udf_values_XML=N'<?xml version="1.0" encoding="UTF-16"?><data></data>',@academic_person_udf_XML=N'<?xml version="1.0" encoding="UTF-16"?><data></data>',@newcomer_details_XML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@enquiry_documents_xml=NULL,@subject_details_XML='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>',@proficiency_in_english_xml='<?xml version="1.0" encoding="ISO-8859-1"?><data></data>'