//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ATfile {
    
    private ATfileHeader headerField;
    
    private ATfilePupil[] aTFpupilDataField;
    
    /// <remarks/>
    public ATfileHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pupil", IsNullable=false)]
    public ATfilePupil[] ATFpupilData {
        get {
            return this.aTFpupilDataField;
        }
        set {
            this.aTFpupilDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfileHeader {
    
    private string documentNameField;
    
    private decimal aTFversionField;
    
    private System.DateTime dateTimeField;
    
    private string documentQualifierField;
    
    private string supplierIDField;
    
    private ATfileHeaderSourceSchool sourceSchoolField;
    
    private ATfileHeaderDestSchool destSchoolField;
    
    private ATfileHeaderSuppInfo suppInfoField;
    
    /// <remarks/>
    public string DocumentName {
        get {
            return this.documentNameField;
        }
        set {
            this.documentNameField = value;
        }
    }
    
    /// <remarks/>
    public decimal ATFversion {
        get {
            return this.aTFversionField;
        }
        set {
            this.aTFversionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentQualifier {
        get {
            return this.documentQualifierField;
        }
        set {
            this.documentQualifierField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierID {
        get {
            return this.supplierIDField;
        }
        set {
            this.supplierIDField = value;
        }
    }
    
    /// <remarks/>
    public ATfileHeaderSourceSchool SourceSchool {
        get {
            return this.sourceSchoolField;
        }
        set {
            this.sourceSchoolField = value;
        }
    }
    
    /// <remarks/>
    public ATfileHeaderDestSchool DestSchool {
        get {
            return this.destSchoolField;
        }
        set {
            this.destSchoolField = value;
        }
    }
    
    /// <remarks/>
    public ATfileHeaderSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfileHeaderSourceSchool {
    
    private ushort lEAField;
    
    private ushort estabField;
    
    private uint uRNField;
    
    private string schoolNameField;
    
    private ushort academicYearField;
    
    /// <remarks/>
    public ushort LEA {
        get {
            return this.lEAField;
        }
        set {
            this.lEAField = value;
        }
    }
    
    /// <remarks/>
    public ushort Estab {
        get {
            return this.estabField;
        }
        set {
            this.estabField = value;
        }
    }
    
    /// <remarks/>
    public uint URN {
        get {
            return this.uRNField;
        }
        set {
            this.uRNField = value;
        }
    }
    
    /// <remarks/>
    public string SchoolName {
        get {
            return this.schoolNameField;
        }
        set {
            this.schoolNameField = value;
        }
    }
    
    /// <remarks/>
    public ushort AcademicYear {
        get {
            return this.academicYearField;
        }
        set {
            this.academicYearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfileHeaderDestSchool {
    
    private byte lEAField;
    
    private ushort estabField;
    
    private uint uRNField;
    
    /// <remarks/>
    public byte LEA {
        get {
            return this.lEAField;
        }
        set {
            this.lEAField = value;
        }
    }
    
    /// <remarks/>
    public ushort Estab {
        get {
            return this.estabField;
        }
        set {
            this.estabField = value;
        }
    }
    
    /// <remarks/>
    public uint URN {
        get {
            return this.uRNField;
        }
        set {
            this.uRNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfileHeaderSuppInfo {
    
    private string suppIDField;
    
    private string[] annotationField;
    
    private string[] fooField;
    
    private string morefooField;
    
    private ATfileHeaderSuppInfoNestedfoo nestedfooField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("documentation", IsNullable=false)]
    public string[] annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("foo")]
    public string[] foo {
        get {
            return this.fooField;
        }
        set {
            this.fooField = value;
        }
    }
    
    /// <remarks/>
    public string morefoo {
        get {
            return this.morefooField;
        }
        set {
            this.morefooField = value;
        }
    }
    
    /// <remarks/>
    public ATfileHeaderSuppInfoNestedfoo nestedfoo {
        get {
            return this.nestedfooField;
        }
        set {
            this.nestedfooField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfileHeaderSuppInfoNestedfoo {
    
    private string lastNameField;
    
    private string firstNameField;
    
    private string streetField;
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupil {
    
    private string applicationReferenceField;
    
    private string uPNField;
    
    private string uniqueLearnerNumberField;
    
    private string uCIField;
    
    private string surnameField;
    
    private string forenameField;
    
    private System.DateTime dOBField;
    
    private string genderField;
    
    private ATfilePupilBasicDetails basicDetailsField;
    
    private ATfilePupilFSMhistory fSMhistoryField;
    
    private ATfilePupilLookedAfter lookedAfterField;
    
    private ATfilePupilSENhistory sENhistoryField;
    
    private ATfilePupilAdmissions admissionsField;
    
    private ATfilePupilAddress addressField;
    
    private ATfilePupilPhone[] phonesField;
    
    private string emailField;
    
    private ATfilePupilContact[] contactsField;
    
    private ATfilePupilSchoolHistory schoolHistoryField;
    
    private ATfilePupilSuppInfo suppInfoField;
    
    private ATfilePupilExternalExaminationResult[] externalExaminationResultsField;
    
    /// <remarks/>
    public string ApplicationReference {
        get {
            return this.applicationReferenceField;
        }
        set {
            this.applicationReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string UPN {
        get {
            return this.uPNField;
        }
        set {
            this.uPNField = value;
        }
    }
    
    /// <remarks/>
    public string UniqueLearnerNumber {
        get {
            return this.uniqueLearnerNumberField;
        }
        set {
            this.uniqueLearnerNumberField = value;
        }
    }
    
    /// <remarks/>
    public string UCI {
        get {
            return this.uCIField;
        }
        set {
            this.uCIField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Forename {
        get {
            return this.forenameField;
        }
        set {
            this.forenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilBasicDetails BasicDetails {
        get {
            return this.basicDetailsField;
        }
        set {
            this.basicDetailsField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilFSMhistory FSMhistory {
        get {
            return this.fSMhistoryField;
        }
        set {
            this.fSMhistoryField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilLookedAfter LookedAfter {
        get {
            return this.lookedAfterField;
        }
        set {
            this.lookedAfterField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilSENhistory SENhistory {
        get {
            return this.sENhistoryField;
        }
        set {
            this.sENhistoryField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilAdmissions Admissions {
        get {
            return this.admissionsField;
        }
        set {
            this.admissionsField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Phone", IsNullable=false)]
    public ATfilePupilPhone[] Phones {
        get {
            return this.phonesField;
        }
        set {
            this.phonesField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Contact", IsNullable=false)]
    public ATfilePupilContact[] Contacts {
        get {
            return this.contactsField;
        }
        set {
            this.contactsField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilSchoolHistory SchoolHistory {
        get {
            return this.schoolHistoryField;
        }
        set {
            this.schoolHistoryField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ExternalExaminationResult", IsNullable=false)]
    public ATfilePupilExternalExaminationResult[] ExternalExaminationResults {
        get {
            return this.externalExaminationResultsField;
        }
        set {
            this.externalExaminationResultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetails {
    
    private string uPNField;
    
    private string preferredSurnameField;
    
    private string formerSurnameField;
    
    private string preferredForenameField;
    
    private string middleNamesField;
    
    private byte nCyearActualField;
    
    private ATfilePupilBasicDetailsEnglishProficiencies englishProficienciesField;
    
    private string countryofBirthField;
    
    private ATfilePupilBasicDetailsNationalities nationalitiesField;
    
    private string ethnicityField;
    
    private string ethnicitySourceField;
    
    private ATfilePupilBasicDetailsType[] languagesField;
    
    private string serviceChildField;
    
    private bool medicalFlagField;
    
    private string[] disabilitiesField;
    
    private ATfilePupilBasicDetailsSuppInfo suppInfoField;
    
    /// <remarks/>
    public string UPN {
        get {
            return this.uPNField;
        }
        set {
            this.uPNField = value;
        }
    }
    
    /// <remarks/>
    public string PreferredSurname {
        get {
            return this.preferredSurnameField;
        }
        set {
            this.preferredSurnameField = value;
        }
    }
    
    /// <remarks/>
    public string FormerSurname {
        get {
            return this.formerSurnameField;
        }
        set {
            this.formerSurnameField = value;
        }
    }
    
    /// <remarks/>
    public string PreferredForename {
        get {
            return this.preferredForenameField;
        }
        set {
            this.preferredForenameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleNames {
        get {
            return this.middleNamesField;
        }
        set {
            this.middleNamesField = value;
        }
    }
    
    /// <remarks/>
    public byte NCyearActual {
        get {
            return this.nCyearActualField;
        }
        set {
            this.nCyearActualField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilBasicDetailsEnglishProficiencies EnglishProficiencies {
        get {
            return this.englishProficienciesField;
        }
        set {
            this.englishProficienciesField = value;
        }
    }
    
    /// <remarks/>
    public string CountryofBirth {
        get {
            return this.countryofBirthField;
        }
        set {
            this.countryofBirthField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilBasicDetailsNationalities Nationalities {
        get {
            return this.nationalitiesField;
        }
        set {
            this.nationalitiesField = value;
        }
    }
    
    /// <remarks/>
    public string Ethnicity {
        get {
            return this.ethnicityField;
        }
        set {
            this.ethnicityField = value;
        }
    }
    
    /// <remarks/>
    public string EthnicitySource {
        get {
            return this.ethnicitySourceField;
        }
        set {
            this.ethnicitySourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
    public ATfilePupilBasicDetailsType[] Languages {
        get {
            return this.languagesField;
        }
        set {
            this.languagesField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceChild {
        get {
            return this.serviceChildField;
        }
        set {
            this.serviceChildField = value;
        }
    }
    
    /// <remarks/>
    public bool MedicalFlag {
        get {
            return this.medicalFlagField;
        }
        set {
            this.medicalFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Disability", IsNullable=false)]
    public string[] Disabilities {
        get {
            return this.disabilitiesField;
        }
        set {
            this.disabilitiesField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilBasicDetailsSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetailsEnglishProficiencies {
    
    private ATfilePupilBasicDetailsEnglishProficienciesEnglishProficiency englishProficiencyField;
    
    /// <remarks/>
    public ATfilePupilBasicDetailsEnglishProficienciesEnglishProficiency EnglishProficiency {
        get {
            return this.englishProficiencyField;
        }
        set {
            this.englishProficiencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetailsEnglishProficienciesEnglishProficiency {
    
    private string proficiencyInEnglishField;
    
    private System.DateTime proficiencyInEnglishDateField;
    
    /// <remarks/>
    public string ProficiencyInEnglish {
        get {
            return this.proficiencyInEnglishField;
        }
        set {
            this.proficiencyInEnglishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ProficiencyInEnglishDate {
        get {
            return this.proficiencyInEnglishDateField;
        }
        set {
            this.proficiencyInEnglishDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetailsNationalities {
    
    private string nationalityField;
    
    /// <remarks/>
    public string Nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetailsType {
    
    private string languageTypeField;
    
    private string languageField;
    
    /// <remarks/>
    public string LanguageType {
        get {
            return this.languageTypeField;
        }
        set {
            this.languageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilBasicDetailsSuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilFSMhistory {
    
    private System.DateTime fSMreviewDateField;
    
    private ATfilePupilFSMhistoryFSMinstance[] fSMinstanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FSMreviewDate {
        get {
            return this.fSMreviewDateField;
        }
        set {
            this.fSMreviewDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FSMinstance")]
    public ATfilePupilFSMhistoryFSMinstance[] FSMinstance {
        get {
            return this.fSMinstanceField;
        }
        set {
            this.fSMinstanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilFSMhistoryFSMinstance {
    
    private System.DateTime fSMstartDateField;
    
    private System.DateTime fSMendDateField;
    
    private bool fSMendDateFieldSpecified;
    
    private string uKcountryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FSMstartDate {
        get {
            return this.fSMstartDateField;
        }
        set {
            this.fSMstartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FSMendDate {
        get {
            return this.fSMendDateField;
        }
        set {
            this.fSMendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FSMendDateSpecified {
        get {
            return this.fSMendDateFieldSpecified;
        }
        set {
            this.fSMendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string UKcountry {
        get {
            return this.uKcountryField;
        }
        set {
            this.uKcountryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilLookedAfter {
    
    private bool inCareField;
    
    private ushort careAuthorityField;
    
    /// <remarks/>
    public bool InCare {
        get {
            return this.inCareField;
        }
        set {
            this.inCareField = value;
        }
    }
    
    /// <remarks/>
    public ushort CareAuthority {
        get {
            return this.careAuthorityField;
        }
        set {
            this.careAuthorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSENhistory {
    
    private ATfilePupilSENhistorySEN sENField;
    
    private ATfilePupilSENhistorySENneed[] sENneedsField;
    
    private ATfilePupilSENhistorySuppInfo suppInfoField;
    
    /// <remarks/>
    public ATfilePupilSENhistorySEN SEN {
        get {
            return this.sENField;
        }
        set {
            this.sENField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SENneed", IsNullable=false)]
    public ATfilePupilSENhistorySENneed[] SENneeds {
        get {
            return this.sENneedsField;
        }
        set {
            this.sENneedsField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilSENhistorySuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSENhistorySEN {
    
    private System.DateTime startDateField;
    
    private string sENprovisionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public string SENprovision {
        get {
            return this.sENprovisionField;
        }
        set {
            this.sENprovisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSENhistorySENneed {
    
    private System.DateTime needStartDateField;
    
    private System.DateTime needEndDateField;
    
    private byte sENtypeRankField;
    
    private string sENtypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NeedStartDate {
        get {
            return this.needStartDateField;
        }
        set {
            this.needStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime NeedEndDate {
        get {
            return this.needEndDateField;
        }
        set {
            this.needEndDateField = value;
        }
    }
    
    /// <remarks/>
    public byte SENtypeRank {
        get {
            return this.sENtypeRankField;
        }
        set {
            this.sENtypeRankField = value;
        }
    }
    
    /// <remarks/>
    public string SENtype {
        get {
            return this.sENtypeField;
        }
        set {
            this.sENtypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSENhistorySuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilAdmissions {
    
    private bool acceptField;
    
    /// <remarks/>
    public bool Accept {
        get {
            return this.acceptField;
        }
        set {
            this.acceptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilAddress {
    
    private ATfilePupilAddressBS7666Address bS7666AddressField;
    
    private ATfilePupilAddressAddressLines addressLinesField;
    
    private string countyField;
    
    private string postCodeField;
    
    private ushort zipField;
    
    private string countryField;
    
    private decimal eastingField;
    
    private decimal northingField;
    
    private ATfilePupilAddressSuppInfo suppInfoField;
    
    /// <remarks/>
    public ATfilePupilAddressBS7666Address BS7666Address {
        get {
            return this.bS7666AddressField;
        }
        set {
            this.bS7666AddressField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilAddressAddressLines AddressLines {
        get {
            return this.addressLinesField;
        }
        set {
            this.addressLinesField = value;
        }
    }
    
    /// <remarks/>
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    public ushort Zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public decimal Easting {
        get {
            return this.eastingField;
        }
        set {
            this.eastingField = value;
        }
    }
    
    /// <remarks/>
    public decimal Northing {
        get {
            return this.northingField;
        }
        set {
            this.northingField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilAddressSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilAddressBS7666Address {
    
    private string sAONField;
    
    private byte pAONField;
    
    private string streetField;
    
    private string localityField;
    
    private string townField;
    
    private string administrativeAreaField;
    
    private string postTownField;
    
    private uint uniquePropertyReferenceNumberField;
    
    /// <remarks/>
    public string SAON {
        get {
            return this.sAONField;
        }
        set {
            this.sAONField = value;
        }
    }
    
    /// <remarks/>
    public byte PAON {
        get {
            return this.pAONField;
        }
        set {
            this.pAONField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string Locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    public string Town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    /// <remarks/>
    public string AdministrativeArea {
        get {
            return this.administrativeAreaField;
        }
        set {
            this.administrativeAreaField = value;
        }
    }
    
    /// <remarks/>
    public string PostTown {
        get {
            return this.postTownField;
        }
        set {
            this.postTownField = value;
        }
    }
    
    /// <remarks/>
    public uint UniquePropertyReferenceNumber {
        get {
            return this.uniquePropertyReferenceNumberField;
        }
        set {
            this.uniquePropertyReferenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilAddressAddressLines {
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string addressLine3Field;
    
    private string addressLine4Field;
    
    private string addressLine5Field;
    
    /// <remarks/>
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine4 {
        get {
            return this.addressLine4Field;
        }
        set {
            this.addressLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine5 {
        get {
            return this.addressLine5Field;
        }
        set {
            this.addressLine5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilAddressSuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilPhone {
    
    private string telephoneTypeField;
    
    private string phoneNoField;
    
    /// <remarks/>
    public string TelephoneType {
        get {
            return this.telephoneTypeField;
        }
        set {
            this.telephoneTypeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNo {
        get {
            return this.phoneNoField;
        }
        set {
            this.phoneNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContact {
    
    private byte orderField;
    
    private string titleField;
    
    private string surnameField;
    
    private string forenameField;
    
    private string middleNamesField;
    
    private string genderField;
    
    private string relationshipField;
    
    private bool responsibilityField;
    
    private ATfilePupilContactAddress addressField;
    
    private ATfilePupilContactPhones phonesField;
    
    private string emailField;
    
    private ATfilePupilContactSuppInfo suppInfoField;
    
    /// <remarks/>
    public byte Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Forename {
        get {
            return this.forenameField;
        }
        set {
            this.forenameField = value;
        }
    }
    
    /// <remarks/>
    public string MiddleNames {
        get {
            return this.middleNamesField;
        }
        set {
            this.middleNamesField = value;
        }
    }
    
    /// <remarks/>
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public string Relationship {
        get {
            return this.relationshipField;
        }
        set {
            this.relationshipField = value;
        }
    }
    
    /// <remarks/>
    public bool Responsibility {
        get {
            return this.responsibilityField;
        }
        set {
            this.responsibilityField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilContactAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilContactPhones Phones {
        get {
            return this.phonesField;
        }
        set {
            this.phonesField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilContactSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactAddress {
    
    private ATfilePupilContactAddressBS7666Address bS7666AddressField;
    
    private ATfilePupilContactAddressAddressLines addressLinesField;
    
    private string countyField;
    
    private string postCodeField;
    
    private ushort zipField;
    
    private bool zipFieldSpecified;
    
    private string countryField;
    
    private decimal eastingField;
    
    private bool eastingFieldSpecified;
    
    private decimal northingField;
    
    private bool northingFieldSpecified;
    
    private bool addressAsPupilField;
    
    private bool addressAsPupilFieldSpecified;
    
    /// <remarks/>
    public ATfilePupilContactAddressBS7666Address BS7666Address {
        get {
            return this.bS7666AddressField;
        }
        set {
            this.bS7666AddressField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilContactAddressAddressLines AddressLines {
        get {
            return this.addressLinesField;
        }
        set {
            this.addressLinesField = value;
        }
    }
    
    /// <remarks/>
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    public ushort Zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZipSpecified {
        get {
            return this.zipFieldSpecified;
        }
        set {
            this.zipFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public decimal Easting {
        get {
            return this.eastingField;
        }
        set {
            this.eastingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EastingSpecified {
        get {
            return this.eastingFieldSpecified;
        }
        set {
            this.eastingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Northing {
        get {
            return this.northingField;
        }
        set {
            this.northingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NorthingSpecified {
        get {
            return this.northingFieldSpecified;
        }
        set {
            this.northingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AddressAsPupil {
        get {
            return this.addressAsPupilField;
        }
        set {
            this.addressAsPupilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddressAsPupilSpecified {
        get {
            return this.addressAsPupilFieldSpecified;
        }
        set {
            this.addressAsPupilFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactAddressBS7666Address {
    
    private string sAONField;
    
    private byte pAONField;
    
    private string streetField;
    
    private string localityField;
    
    private string townField;
    
    private string administrativeAreaField;
    
    private string postTownField;
    
    private uint uniquePropertyReferenceNumberField;
    
    /// <remarks/>
    public string SAON {
        get {
            return this.sAONField;
        }
        set {
            this.sAONField = value;
        }
    }
    
    /// <remarks/>
    public byte PAON {
        get {
            return this.pAONField;
        }
        set {
            this.pAONField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string Locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    public string Town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    /// <remarks/>
    public string AdministrativeArea {
        get {
            return this.administrativeAreaField;
        }
        set {
            this.administrativeAreaField = value;
        }
    }
    
    /// <remarks/>
    public string PostTown {
        get {
            return this.postTownField;
        }
        set {
            this.postTownField = value;
        }
    }
    
    /// <remarks/>
    public uint UniquePropertyReferenceNumber {
        get {
            return this.uniquePropertyReferenceNumberField;
        }
        set {
            this.uniquePropertyReferenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactAddressAddressLines {
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string addressLine3Field;
    
    private string addressLine4Field;
    
    private string addressLine5Field;
    
    /// <remarks/>
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine4 {
        get {
            return this.addressLine4Field;
        }
        set {
            this.addressLine4Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressLine5 {
        get {
            return this.addressLine5Field;
        }
        set {
            this.addressLine5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactPhones {
    
    private ATfilePupilContactPhonesPhone phoneField;
    
    /// <remarks/>
    public ATfilePupilContactPhonesPhone Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactPhonesPhone {
    
    private string telephoneTypeField;
    
    private string phoneNoField;
    
    /// <remarks/>
    public string TelephoneType {
        get {
            return this.telephoneTypeField;
        }
        set {
            this.telephoneTypeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNo {
        get {
            return this.phoneNoField;
        }
        set {
            this.phoneNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilContactSuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSchoolHistory {
    
    private ATfilePupilSchoolHistorySchool schoolField;
    
    /// <remarks/>
    public ATfilePupilSchoolHistorySchool School {
        get {
            return this.schoolField;
        }
        set {
            this.schoolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSchoolHistorySchool {
    
    private ushort lEAField;
    
    private ushort estabField;
    
    private uint uRNField;
    
    private string schoolNameField;
    
    private System.DateTime entryDateField;
    
    private System.DateTime leavingDateField;
    
    private string leavingReasonField;
    
    private ATfilePupilSchoolHistorySchoolSuppInfo suppInfoField;
    
    /// <remarks/>
    public ushort LEA {
        get {
            return this.lEAField;
        }
        set {
            this.lEAField = value;
        }
    }
    
    /// <remarks/>
    public ushort Estab {
        get {
            return this.estabField;
        }
        set {
            this.estabField = value;
        }
    }
    
    /// <remarks/>
    public uint URN {
        get {
            return this.uRNField;
        }
        set {
            this.uRNField = value;
        }
    }
    
    /// <remarks/>
    public string SchoolName {
        get {
            return this.schoolNameField;
        }
        set {
            this.schoolNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EntryDate {
        get {
            return this.entryDateField;
        }
        set {
            this.entryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LeavingDate {
        get {
            return this.leavingDateField;
        }
        set {
            this.leavingDateField = value;
        }
    }
    
    /// <remarks/>
    public string LeavingReason {
        get {
            return this.leavingReasonField;
        }
        set {
            this.leavingReasonField = value;
        }
    }
    
    /// <remarks/>
    public ATfilePupilSchoolHistorySchoolSuppInfo SuppInfo {
        get {
            return this.suppInfoField;
        }
        set {
            this.suppInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSchoolHistorySchoolSuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilSuppInfo {
    
    private string suppIDField;
    
    /// <remarks/>
    public string SuppID {
        get {
            return this.suppIDField;
        }
        set {
            this.suppIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ATfilePupilExternalExaminationResult {
    
    private string boardCodeField;
    
    private string levelField;
    
    private string subjectCodeField;
    
    private string schoolField;
    
    private ushort yearField;
    
    private string resultField;
    
    private string resultTypeField;
    
    private uint qANField;
    
    /// <remarks/>
    public string BoardCode {
        get {
            return this.boardCodeField;
        }
        set {
            this.boardCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string SubjectCode {
        get {
            return this.subjectCodeField;
        }
        set {
            this.subjectCodeField = value;
        }
    }
    
    /// <remarks/>
    public string School {
        get {
            return this.schoolField;
        }
        set {
            this.schoolField = value;
        }
    }
    
    /// <remarks/>
    public ushort Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public string ResultType {
        get {
            return this.resultTypeField;
        }
        set {
            this.resultTypeField = value;
        }
    }
    
    /// <remarks/>
    public uint QAN {
        get {
            return this.qANField;
        }
        set {
            this.qANField = value;
        }
    }
}
